apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hostname
  labels:
    app: hostname
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      - key: tier
        operator: NotIn
        values: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: docker.io/brokenpen/hostname:v1